DROP USER IF EXISTS 'leoadmin'@'localhost';
DROP USER IF EXISTS 'racheladmin'@'localhost';
DROP USER IF EXISTS 'appadmin'@'localhost';
DROP USER IF EXISTS 'appclient'@'localhost';
DROP DATABASE IF EXISTS soccerdb;
CREATE DATABASE soccerdb;
USE soccerdb; 
source setup.sql;
source load-data.sql;
source setup-passwords.sql;
source setup-routines.sql;
source grant-permissions.sql;
source queries.sql;